[paths]
game_dir         = E:\SteamLibrary\steamapps\common\Halo The Master Chief Collection\halo2\prebuild
intermediate_dir = F:\Videos\h2a_cg
export_dir       = D:\Jiayu\Videos
export_name      = Halo.2.Anniversary.Cinematics
; subtitle_dir     = F:\Videos\h2a_cg\subtitles
